name: 🧪 Frontend CI (Dev Branch)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - name: ⚙️ Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install Dependencies
        run: npm install
        working-directory: frontend

      - name: 🛠️ Build App
        run: npm run build
        working-directory: frontend
